/*
 * HomeConstants
 */

export const CHANGE_USERNAME = 'boilerplate/Home/CHANGE_USERNAME';
export const SET_CELESTIAL_DATA = 'GENERAL:SET_CELESTIAL_DATA';
export const UPDATE_PLANET_POSITION = 'GENERAL:UPDATE_PLANET_POSITION';
export const MOVE_TO = 'GENERAL:MOVE_TO';
